name: Frontend unit tests

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build dockerfile
      run: docker build -t jz23/docker_course_prod_workflow -f Dockerfile.dev .
    - name: Run tests
      run: docker run -e CI=true jz23/docker_course_prod_workflow npm test